---
# golangci-lint configuration
#
run:
  timeout: 10m
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - cyclop
    - dogsled
    - errorlint
    - exportloopref
    - goconst
    - gocritic
    - gomnd
    - gosec
    - misspell
    - nilerr
    - predeclared
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return
          - assign
          - operation
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  staticcheck:
    go: "1.16"
  stylecheck:
    go: "1.16"
  unparam:
    check-exported: true
  unused:
    check-exported: false
